# Use uma imagem Node.js como a base
FROM node:18-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia package.json e package-lock.json (ou yarn.lock)
# Isso otimiza o cache do Docker, para não reinstalar tudo a cada mudança de código
COPY package*.json ./

# Instala as dependências
RUN npm install

# Expõe a porta em que o aplicativo React roda
EXPOSE 3000

# Comando para iniciar o servidor de desenvolvimento React
CMD ["npm", "start"]