# Generated by Django 4.2.23 on 2025-08-10 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('numero_sus', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('CRIADA', 'Criada'), ('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CONCLUIDA', 'Concluída')], max_length=20)),
                ('tipo_procedimento', models.CharField(choices=[('CONSULTA', 'Consulta'), ('EXAME', 'Exame'), ('CIRURGIA', 'Cirurgia'), ('INTERNACAO', 'Internação'), ('MEDICAMENTO', 'Medicamento'), ('OUTRO', 'Outro')], max_length=20)),
                ('procedimento', models.CharField(help_text='Nome ou código do procedimento solicitado.', max_length=255)),
                ('cid_10', models.CharField(max_length=6)),
                ('justificativa', models.TextField(help_text='Justificativa textual para a solicitação (pode ser gerada por IA).')),
                ('status', models.CharField(choices=[('CRIADA', 'Criada'), ('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CONCLUIDA', 'Concluída')], default='CRIADA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a solicitação foi criada.')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização.')),
                ('metadados_ia', models.JSONField(blank=True, help_text='Metadados da interação com a IA, como notas técnicas usadas.', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
