# Generated by Django 4.2.23 on 2025-08-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillsense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='descricao_medica',
            field=models.CharField(default='Descrição Médica', max_length=500),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
