# Generated by Django 4.2.23 on 2025-08-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fillsense', '0002_solicitacao_descricao_medica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='descricao_medica',
        ),
    ]
