# Generated by Django 4.2.23 on 2025-08-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillsense', '0003_remove_solicitacao_descricao_medica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Justificativa textual para a solicitação (pode ser gerada por IA).', null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='metadados_ia',
            field=models.JSONField(default=dict, help_text='Metadados da interação com a IA, como notas técnicas usadas.'),
        ),
    ]
