# Generated by Django 4.2.23 on 2025-08-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillsense', '0004_alter_solicitacao_justificativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='protocolo',
            field=models.CharField(default='FS-XXXX-YYYYY', editable=False, help_text='Protocolo único da solicitação (FS-ANO-ID).', max_length=20, unique=True),
        ),
    ]
