# Generated by Django 4.2.23 on 2025-08-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillsense', '0006_alter_solicitacao_protocolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='cid_10',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='numero_sus',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='tipo_procedimento',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='descricao_medica',
            field=models.TextField(blank=True, help_text='Descrição médica inicial preenchida manualmente pelo o usuário.', null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Justificativa textual para a solicitação (gerada por IA e revisada pelo usuário).', null=True),
        ),
    ]
