# Generated by Django 4.2.25 on 2025-10-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillsense', '0007_remove_solicitacao_cid_10_remove_solicitacao_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('codigo', models.CharField(help_text='Código do procedimento em ASCII', max_length=255, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Texto legível do procedimento, é o que será exibido para o usuário', max_length=255)),
            ],
        ),
    ]
