# Generated by Django 4.2.25 on 2025-10-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillsense', '0008_procedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='procedimento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fillsense.procedimento'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='procedimento',
            field=models.CharField(max_length=255),
        ),
    ]
