# Generated by Django 4.2.25 on 2025-10-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillsense', '0009_solicitacao_procedimento_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='procedimento',
            field=models.CharField(help_text='Nome ou código do procedimento solicitado.', max_length=255),
        ),
    ]
